sudo: required
dist: trusty

env:
  global:
    # eratosthenes library management system url (encrypted) --> LIBRARY_URL
    - secure: "DX1KR4VH1AwthSZ/6me6y8EB/xCf7kH+hXyacOiIwHmxPe7xR/+v7nht1Dlspco0nonv7hlF8yCilF2f3cIMHQlmyg9s1kuVZ4QtC8O9+ZkVQ6fDhhH7HKYNUKjhKO7eT5a+RD7YCXQYQSfDfJ35cWeK3vAast3zWK2pnmdKXhc="
    # codebender compiler url (encrypted) --> COMPILER_URL
    - secure: "QUYKE9qjXxeCWZPl+CQpIvj3J9Bz9aVu9jo1m+EDjaQ3gXwQ+kXTyZ68eDeLLCFq8s5IEcsNdE6X7wyBh+eu6rzEU5EwvGMqPdIpXxnhkzTbb8d2KRCScwkglrB/Dbh1Ovhq0+CdaSkLSQBQvOuxkqgGNf1Oophws6eG4iCIZKQ="

before_script:
  - sudo chmod +x scripts/travis_install.sh
  - scripts/travis_install.sh
  - cd /opt/codebender/builder/Symfony
  - sudo chmod -R 777 app/cache app/logs
  - echo 'error_reporting =  E_ALL' >> /etc/php5/cli/conf.d/travis.ini
  - cd /opt/codebender/builder
  - sudo chmod +x scripts/travis_apache_install.sh
  - scripts/travis_apache_install.sh
  - cd /opt/codebender/builder/Symfony

script:
  - mkdir -p build/logs
  - bin/phpunit -c app/ --coverage-clover build/logs/clover.xml --stderr
  - bin/phpcpd --log-pmd build/pmd-cpd.xml --exclude app --exclude vendor --names-exclude *Test.php -n .
  - bin/phpmd src/Codebender/ xml cleancode,codesize,design,naming,unusedcode --exclude *Test.php --reportfile build/pmd.xml

after_script:
  - php composer.phar install --dev
  - php bin/coveralls -v

notifications:
  irc: "chat.freenode.net#codebender.cc"
